CREATE DATABASE `dbtuts` ;

CREATE TABLE `users` (
`user_id` INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR(45) NOT NULL ,
`nickname` VARCHAR(25) NOT NULL,
`email` VARCHAR(45) NOT NULL,
`home` VARCHAR(100) DEFAULT NULL,
`gender` VARCHAR(15) NOT NULL,
`number` VARCHAR(15) NOT NULL,
`comment` VARCHAR(200) DEFAULT NULL
) ENGINE = InnoDB;